apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nb-chart.fullname" . }}
  labels:
    {{- include "nb-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nb-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nb-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nb-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            initialDelaySeconds: 10
#            periodSeconds: 30
#            exec:
#              command:
#                - /bin/sh
#                - -c
#                - |
#                  CACHE_SERVER=$(awk 'BEGIN {print ENVIRON["cache.server"]}');
#                  KAFKA_SERVER=$(awk 'BEGIN {print ENVIRON["metadata.broker.list"]}');
#                  if [ -z "$CACHE_SERVER" -o -z "$KAFKA_SERVER" ]
#                    then
#                    echo "env var 'cache.server' OR 'metadata.broker.list' is not set"
#                    exit 1
#                  fi

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
